---
- name: create backend app dir
  file:
    path: ~/backend-app
    state: directory
    

- name: unzip backend files
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: install node deps
  shell: | 
    cd ~/backend-app
    npm i

- name: Start pm2
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
